export enum typesColorsEnum {
  Acier = "bg-slate-100 text-slate-800",
  Combat = "bg-red-500 text-red-800",
  Dragon = "bg-sky-100 text-sky-800",
  Eau = "bg-blue-100 text-blue-800",
  Electrik = "bg-yellow-500 text-yellow-800",
  Fée = "bg-pink-100 text-pink-800",
  Feu = "bg-red-100 text-red-800",
  Glace = "bg-blue-100 text-blue-700",
  Insecte = "bg-yellow-100 text-yellow-800",
  Normal = "bg-yellow-100 text-gray-800",
  Plante = "bg-green-100 text-green-800",
  Poison = "bg-purple-700 text-purple-100",
  Psy = "bg-purple-100 text-purple-800",
  Roche = "bg-amber-900 text-amber-950",
  Sol = "bg-amber-600 text-amber-800",
  Spectre = "bg-purple-800 text-purple-100",
  Ténèbres = "bg-yellow-1400 text-yellow-800",
  Vol = "bg-sky-200 text-sky-800",
}

export enum pokemonTypesEnum {
  Acier = "Acier",
  Combat = "Combat",
  Dragon = "Dragon",
  Eau = "Eau",
  Electrik = "Electrik",
  Fée = "Fée",
  Feu = "Feu",
  Glace = "Glace",
  Insecte = "Insecte",
  Normal = "Normal",
  Plante = "Plante",
  Poison = "Poison",
  Psy = "Psy",
  Roche = "Roche",
  Sol = "Sol",
  Spectre = "Spectre",
  Ténèbres = "Ténèbres",
  Vol = "Vol",
}