import ComparatorProvider from "@/lib/providers/ComparatorProvider";
import PokemonsProvider from "@/lib/providers/PokemonsProviders";
import PokemonsListProvider from "@/lib/providers/PokemonstListProvider";
import TypesProvider from "@/lib/providers/TypesProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import GenNavigation from "@/app/components/Layout/GenNavigation";
import Header from "@/app/components/Layout/Header";
import "@/app/style/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const generations = await fetch("https://tyradex.vercel.app/api/v1/gen", {
    cache: "force-cache",
  }).then((res) => res.json());
  const pokemons = await fetch("https://tyradex.vercel.app/api/v1/pokemon", {
    cache: "force-cache",
  }).then((res) => res.json());
  const types = await fetch("https://tyradex.vercel.app/api/v1/types", {
    cache: "force-cache",
  }).then((res) => res.json());

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col gap-2 h-full">
          <PokemonsProvider data={pokemons}>
            <TypesProvider types={types}>
              <ComparatorProvider>
                <Header pokemons={pokemons} generations={generations} />
                <div className="hidden xl:block">
                  <GenNavigation generations={generations} />
                </div>
                <PokemonsListProvider>{children}</PokemonsListProvider>
              </ComparatorProvider>
            </TypesProvider>
          </PokemonsProvider>
        </div>
      </body>
    </html>
  );
}
