version: '3.8'
services:
  app:
    image: front
    container_name: my_pokedex
    build: 
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"